# Etapa 1: Build
FROM golang:1.25.1 AS builder
WORKDIR /app
COPY go.mod ./
COPY . .
RUN go build -o main .

# Etapa 2: Imagem final do OS
FROM debian:bookworm-slim
WORKDIR /app
COPY --from=builder /app/main .
CMD ["./main"]
